# Tactical Zone Definitions
# Coordinates in pitch space (meters)
# Origin: center of pitch (0, 0)
# X-axis: length (goal to goal)
# Y-axis: width (sideline to sideline)

zones:
  zone_14:
    name: "Zone 14"
    description: "Central attacking zone just outside penalty area"
    bounds:
      x_min: 16.5
      x_max: 0.0
      y_min: -9.0
      y_max: 9.0

  half_space_left:
    name: "Left Half-Space"
    description: "Left attacking channel"
    bounds:
      x_min: 0.0
      x_max: -52.5
      y_min: -34.0
      y_max: -9.0

  half_space_right:
    name: "Right Half-Space"
    description: "Right attacking channel"
    bounds:
      x_min: 0.0
      x_max: -52.5
      y_min: 9.0
      y_max: 34.0

  goal_area:
    name: "Goal Area"
    description: "6-yard box and penalty area"
    bounds:
      x_min: 16.5
      x_max: -16.5
      y_min: -20.16
      y_max: 20.16

  penalty_area:
    name: "Penalty Area"
    description: "18-yard box"
    bounds:
      x_min: 16.5
      x_max: -16.5
      y_min: -30.34
      y_max: 30.34
